AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: KC Project Lambda - aribasync
Resources:
  aribasync:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'Lambda function for KC Project'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::495483283172:role/KCLambdaRole'
      Environment:
        Variables:
          REGION: eu-west-1